// <auto-generated />
using EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC.Migrations
{
    [DbContext(typeof(DatabaseAccess))]
    [Migration("20230519094036_addOneToMany")]
    partial class addOneToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EFC.Entities.IngredientEntity", b =>
                {
                    b.Property<string>("IngredientName")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientName");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("EFC.Entities.MenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("EFC.Entities.MenuIngredientEntity", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngredientName")
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId", "IngredientName");

                    b.HasIndex("IngredientName");

                    b.ToTable("MenuIngredientEntity");
                });

            modelBuilder.Entity("EFC.Entities.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReservedByUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ReservedByUsername");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EFC.Entities.UserEntity", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFC.Entities.MenuIngredientEntity", b =>
                {
                    b.HasOne("EFC.Entities.IngredientEntity", "Ingredient")
                        .WithMany("MenuIngredients")
                        .HasForeignKey("IngredientName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC.Entities.MenuEntity", "Menu")
                        .WithMany("MenuIngredients")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("EFC.Entities.ReservationEntity", b =>
                {
                    b.HasOne("EFC.Entities.MenuEntity", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC.Entities.UserEntity", "ReservedBy")
                        .WithMany()
                        .HasForeignKey("ReservedByUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("ReservedBy");
                });

            modelBuilder.Entity("EFC.Entities.IngredientEntity", b =>
                {
                    b.Navigation("MenuIngredients");
                });

            modelBuilder.Entity("EFC.Entities.MenuEntity", b =>
                {
                    b.Navigation("MenuIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
